version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - 🤖 dependabot
    groups:
      docker:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      timezone: America/Chicago
    labels:
      - 🤖 dependabot
    groups:
      gha:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      timezone: America/Chicago
    labels:
      - 🤖 dependabot
    groups:
      javascript:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      timezone: America/Chicago
    labels:
      - 🤖 dependabot
    groups:
      python:
        patterns:
          - "*"
        exclude-patterns:
          - "django-email-relay"
      email-relay:
        patterns:
          - "django-email-relay"
