name: Labels

on:
  schedule:
    # https://crontab.guru/#30_2_*_*_*
    - cron: "30 2 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/labels.yml

      - uses: EndBug/label-sync@v2
        with:
          config-file: |
            https://raw.githubusercontent.com/westerveltco/.github/main/.github/labels.yml
            .github/labels.yml
