x-depends-on-db: &depends-on-db
  db:
    condition: service_healthy

x-default-app: &default-app
  build:
    context: .
    dockerfile: Dockerfile
    target: dev
  env_file: .env
  init: true
  user: "${UID:-1000}:${GID:-1000}"
  volumes:
    - .:/app:cached
  working_dir: /app

services:
  app:
    <<: *default-app
    command: python manage.py runserver 0.0.0.0:8000 --skip-checks
    depends_on: *depends-on-db
    ports:
      - "${DJANGO_PORT:-8000}:8000"

  db:
    image: postgis/postgis:15-3.4
    env_file:
      - .env
    init: true
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: "exit 0"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - .:/app

  tailwind:
    <<: *default-app
    build:
      target: tailwind
    command: python manage.py tailwind --skip-checks watch
    tty: true

  worker:
    <<: *default-app
    command: python manage.py qcluster
    depends_on: *depends-on-db

volumes:
  postgres-data:
