name: examples

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  examples:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v1

      - uses: eifinger/setup-rye@v1
        with:
          enable-cache: true
          cache-prefix: ${{ github.head_ref }}

      - name: Install dependencies
        run: |
          rye sync

      - name: Generate examples
        run: |
          just generate-examples

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Regenerated examples" || exit 0
          git push
