name: test

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  PYTHONUNBUFFERED: "1"
  PYTHON_REQUIREMENTS: requirements-dev.lock
  PYTHON_VERSION: "3.8"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: westerveltco/setup-ci-action@v0
        with:
          python-requirements: ${{ env.PYTHON_REQUIREMENTS }}
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run tests
        run: |
          python -m pytest
